language: node_js
node_js:
  - stable
branches:
  only:
  - source
before_install:
  - openssl aes-256-cbc -K $encrypted_8e945db8c448_key -iv $encrypted_8e945db8c448_iv -in id_rsa.enc -out id_rsa -d
  - npm install -g hexo-cli
install:
  - npm install
script:
  - hexo generate
after_success:
  - git config --global user.name "lewis617"
  - git config --global user.email "897473127@qq.com"
  - hexo deploy
